### ISSUE TITLE
Class 'App\Reset Password' not found

### ISSUE THREAD

**Issue by SayedAkhtar** [mtvbrianking/multi-auth#16]
Getting this error

**Comment by mtvbrianking** [comment]
There's no `ResetPassword` in the `app` namespace

Share **error stack trace**

**Comment by SayedAkhtar** [comment]
I click on forgot password then put the email link after i click the button it giges me this error i have setup my gaurd as customer
![error](https://user-images.githubusercontent.com/11989480/50724118-11f51700-110e-11e9-9c4c-8439667ddc0f.JPG)

**Comment by mtvbrianking** [comment]
Didn't you uninstall the package #15 !

If you want to implement **Multi authentication from 'scratch' using custom guards** [refer](https://github.com/mtvbrianking/multi-auth-diy/commits/master)

![image](https://user-images.githubusercontent.com/5412360/50724200-b1a8aa00-10fa-11e9-9665-1d50cc362831.png)

**Comment by SayedAkhtar** [comment]
I tried to uninstall but I messed it up so I cloned an earlier versions and
now I am getting this error

**Comment by mtvbrianking** [comment]
Do you still want to have multi guards in you project; like

`example.com` <- general/default

`example.com/customers` <- customer side

Or:

`example.com/customers` is a route in general!!

Share with me the routes if possible

`php artisan route:list`

**Comment by SayedAkhtar** [comment]
Nope
Pickfreely.com

Tap on login

**Comment by mtvbrianking** [comment]
You're not using the 'customers' guard

http://pickfreely.com/customers <- 404 Not Found

I suggest you using
http://pickfreely.com/login
Instead of...
http://pickfreely.com/customer/login

http://pickfreely.com/password/reset 
Instead of...
http://pickfreely.com/customer/password/reset 

![image](https://user-images.githubusercontent.com/5412360/50724524-af951a00-10ff-11e9-931f-3a241d8266db.png)

**Comment by SayedAkhtar** [comment]
Actually i do have voyager installed
Using user so I wanted a different route and database table so I am using it
